//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} is not exists. 的本地化字符串。
        /// </summary>
        internal static string Common_ObjectNotExist {
            get {
                return ResourceManager.GetString("Common_ObjectNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The operation failed. 的本地化字符串。
        /// </summary>
        internal static string Common_OperationFailed {
            get {
                return ResourceManager.GetString("Common_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading data failed.Please reload again. 的本地化字符串。
        /// </summary>
        internal static string Common_ReadPageDataFailed {
            get {
                return ResourceManager.GetString("Common_ReadPageDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select one or more item. 的本地化字符串。
        /// </summary>
        internal static string Common_RequiedSelectItem {
            get {
                return ResourceManager.GetString("Common_RequiedSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid parameter 的本地化字符串。
        /// </summary>
        internal static string Common_WrongParameter {
            get {
                return ResourceManager.GetString("Common_WrongParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function name is required. 的本地化字符串。
        /// </summary>
        internal static string Rights_FunctionNameRequired {
            get {
                return ResourceManager.GetString("Rights_FunctionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function url is required. 的本地化字符串。
        /// </summary>
        internal static string Rights_FunctionUrlRequired {
            get {
                return ResourceManager.GetString("Rights_FunctionUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description is required. 的本地化字符串。
        /// </summary>
        internal static string Rights_FunDescRequired {
            get {
                return ResourceManager.GetString("Rights_FunDescRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select one or more rights 的本地化字符串。
        /// </summary>
        internal static string Rights_RequiredSelect {
            get {
                return ResourceManager.GetString("Rights_RequiredSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share failed. 的本地化字符串。
        /// </summary>
        internal static string SettingPermissionFailed {
            get {
                return ResourceManager.GetString("SettingPermissionFailed", resourceCulture);
            }
        }
    }
}
