//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Insourcia.Psychotherapy.Model
{
    public partial class ClinicalServiceNoteRate
    {
        #region Primitive Properties
    
        public virtual int clinicalServiceNoteRateId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> symptomId
        {
            get;
            set;
        }
    
        public virtual string clientRate
        {
            get;
            set;
        }
    
        public virtual string therapistRate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ClinicalServiceID
        {
            get { return _clinicalServiceID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_clinicalServiceID != value)
                    {
                        if (ClinicalService != null && ClinicalService.ClinicalServiceID != value)
                        {
                            ClinicalService = null;
                        }
                        _clinicalServiceID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _clinicalServiceID;
    
        public virtual Nullable<int> TreatmentPlanID
        {
            get { return _treatmentPlanID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_treatmentPlanID != value)
                    {
                        if (TreatmentPlan != null && TreatmentPlan.TreatmentPlanID != value)
                        {
                            TreatmentPlan = null;
                        }
                        _treatmentPlanID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _treatmentPlanID;
    
        public virtual Nullable<bool> isValid
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> createTime
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ClinicalService ClinicalService
        {
            get { return _clinicalService; }
            set
            {
                if (!ReferenceEquals(_clinicalService, value))
                {
                    var previousValue = _clinicalService;
                    _clinicalService = value;
                    FixupClinicalService(previousValue);
                }
            }
        }
        private ClinicalService _clinicalService;
    
        public virtual TreatmentPlan TreatmentPlan
        {
            get { return _treatmentPlan; }
            set
            {
                if (!ReferenceEquals(_treatmentPlan, value))
                {
                    var previousValue = _treatmentPlan;
                    _treatmentPlan = value;
                    FixupTreatmentPlan(previousValue);
                }
            }
        }
        private TreatmentPlan _treatmentPlan;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupClinicalService(ClinicalService previousValue)
        {
            if (previousValue != null && previousValue.ClinicalServiceNoteRates.Contains(this))
            {
                previousValue.ClinicalServiceNoteRates.Remove(this);
            }
    
            if (ClinicalService != null)
            {
                if (!ClinicalService.ClinicalServiceNoteRates.Contains(this))
                {
                    ClinicalService.ClinicalServiceNoteRates.Add(this);
                }
                if (ClinicalServiceID != ClinicalService.ClinicalServiceID)
                {
                    ClinicalServiceID = ClinicalService.ClinicalServiceID;
                }
            }
            else if (!_settingFK)
            {
                ClinicalServiceID = null;
            }
        }
    
        private void FixupTreatmentPlan(TreatmentPlan previousValue)
        {
            if (previousValue != null && previousValue.ClinicalServiceNoteRates.Contains(this))
            {
                previousValue.ClinicalServiceNoteRates.Remove(this);
            }
    
            if (TreatmentPlan != null)
            {
                if (!TreatmentPlan.ClinicalServiceNoteRates.Contains(this))
                {
                    TreatmentPlan.ClinicalServiceNoteRates.Add(this);
                }
                if (TreatmentPlanID != TreatmentPlan.TreatmentPlanID)
                {
                    TreatmentPlanID = TreatmentPlan.TreatmentPlanID;
                }
            }
            else if (!_settingFK)
            {
                TreatmentPlanID = null;
            }
        }

        #endregion
    }
}
