//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Insourcia.Psychotherapy.Model
{
    public partial class TreatmentPlanItem
    {
        #region Primitive Properties
    
        public virtual int ItemID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TreatmentPlanID
        {
            get { return _treatmentPlanID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_treatmentPlanID != value)
                    {
                        if (TreatmentPlan != null && TreatmentPlan.TreatmentPlanID != value)
                        {
                            TreatmentPlan = null;
                        }
                        _treatmentPlanID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _treatmentPlanID;
    
        public virtual Nullable<int> SymptomID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> LongTermGoalID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ObjectiveID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> StrategyID
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreateTime
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastModifiedTime
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsValid
        {
            get;
            set;
        }
    
        public virtual string Count
        {
            get;
            set;
        }
    
        public virtual string Measure
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual TreatmentPlan TreatmentPlan
        {
            get { return _treatmentPlan; }
            set
            {
                if (!ReferenceEquals(_treatmentPlan, value))
                {
                    var previousValue = _treatmentPlan;
                    _treatmentPlan = value;
                    FixupTreatmentPlan(previousValue);
                }
            }
        }
        private TreatmentPlan _treatmentPlan;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupTreatmentPlan(TreatmentPlan previousValue)
        {
            if (previousValue != null && previousValue.TreatmentPlanItems.Contains(this))
            {
                previousValue.TreatmentPlanItems.Remove(this);
            }
    
            if (TreatmentPlan != null)
            {
                if (!TreatmentPlan.TreatmentPlanItems.Contains(this))
                {
                    TreatmentPlan.TreatmentPlanItems.Add(this);
                }
                if (TreatmentPlanID != TreatmentPlan.TreatmentPlanID)
                {
                    TreatmentPlanID = TreatmentPlan.TreatmentPlanID;
                }
            }
            else if (!_settingFK)
            {
                TreatmentPlanID = null;
            }
        }

        #endregion
    }
}
