//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Insourcia.Psychotherapy.Model
{
    public partial class UserFilePermission
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int UserID
        {
            get { return _userID; }
            set
            {
                if (_userID != value)
                {
                    if (User != null && User.UserID != value)
                    {
                        User = null;
                    }
                    _userID = value;
                }
            }
        }
        private int _userID;
    
        public virtual int FileID
        {
            get { return _fileID; }
            set
            {
                if (_fileID != value)
                {
                    if (File != null && File.FileID != value)
                    {
                        File = null;
                    }
                    _fileID = value;
                }
            }
        }
        private int _fileID;
    
        public virtual bool can_read
        {
            get;
            set;
        }
    
        public virtual bool can_write
        {
            get;
            set;
        }
    
        public virtual bool can_remove
        {
            get;
            set;
        }
    
        public virtual bool can_download
        {
            get;
            set;
        }
    
        public virtual bool can_annotate
        {
            get;
            set;
        }
    
        public virtual bool can_upload
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> time_created
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> last_modified
        {
            get;
            set;
        }
    
        public virtual int last_modified_by
        {
            get;
            set;
        }
    
        public virtual bool is_valid
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual File File
        {
            get { return _file; }
            set
            {
                if (!ReferenceEquals(_file, value))
                {
                    var previousValue = _file;
                    _file = value;
                    FixupFile(previousValue);
                }
            }
        }
        private File _file;
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion
        #region Association Fixup
    
        private void FixupFile(File previousValue)
        {
            if (previousValue != null && previousValue.UserFilePermissions.Contains(this))
            {
                previousValue.UserFilePermissions.Remove(this);
            }
    
            if (File != null)
            {
                if (!File.UserFilePermissions.Contains(this))
                {
                    File.UserFilePermissions.Add(this);
                }
                if (FileID != File.FileID)
                {
                    FileID = File.FileID;
                }
            }
        }
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.UserFilePermissions.Contains(this))
            {
                previousValue.UserFilePermissions.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.UserFilePermissions.Contains(this))
                {
                    User.UserFilePermissions.Add(this);
                }
                if (UserID != User.UserID)
                {
                    UserID = User.UserID;
                }
            }
        }

        #endregion
    }
}
