//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Insourcia.Psychotherapy.Model
{
    public partial class Cluster
    {
        #region Primitive Properties
    
        public virtual int ClusterID
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ParientID
        {
            get;
            set;
        }
    
        public virtual string GlanceSummaryAction
        {
            get;
            set;
        }
    
        public virtual string GuideLineAction
        {
            get;
            set;
        }
    
        public virtual string ContinueAction
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastModifiedTime
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsValid
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreateTime
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Symptom> Symptoms
        {
            get
            {
                if (_symptoms == null)
                {
                    var newCollection = new FixupCollection<Symptom>();
                    newCollection.CollectionChanged += FixupSymptoms;
                    _symptoms = newCollection;
                }
                return _symptoms;
            }
            set
            {
                if (!ReferenceEquals(_symptoms, value))
                {
                    var previousValue = _symptoms as FixupCollection<Symptom>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSymptoms;
                    }
                    _symptoms = value;
                    var newValue = value as FixupCollection<Symptom>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSymptoms;
                    }
                }
            }
        }
        private ICollection<Symptom> _symptoms;
    
        public virtual ICollection<GlanceAndGuideline> GlanceAndGuidelines
        {
            get
            {
                if (_glanceAndGuidelines == null)
                {
                    var newCollection = new FixupCollection<GlanceAndGuideline>();
                    newCollection.CollectionChanged += FixupGlanceAndGuidelines;
                    _glanceAndGuidelines = newCollection;
                }
                return _glanceAndGuidelines;
            }
            set
            {
                if (!ReferenceEquals(_glanceAndGuidelines, value))
                {
                    var previousValue = _glanceAndGuidelines as FixupCollection<GlanceAndGuideline>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupGlanceAndGuidelines;
                    }
                    _glanceAndGuidelines = value;
                    var newValue = value as FixupCollection<GlanceAndGuideline>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupGlanceAndGuidelines;
                    }
                }
            }
        }
        private ICollection<GlanceAndGuideline> _glanceAndGuidelines;

        #endregion
        #region Association Fixup
    
        private void FixupSymptoms(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Symptom item in e.NewItems)
                {
                    if (!item.Clusters.Contains(this))
                    {
                        item.Clusters.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Symptom item in e.OldItems)
                {
                    if (item.Clusters.Contains(this))
                    {
                        item.Clusters.Remove(this);
                    }
                }
            }
        }
    
        private void FixupGlanceAndGuidelines(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (GlanceAndGuideline item in e.NewItems)
                {
                    if (!item.Clusters.Contains(this))
                    {
                        item.Clusters.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (GlanceAndGuideline item in e.OldItems)
                {
                    if (item.Clusters.Contains(this))
                    {
                        item.Clusters.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
