//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Insourcia.Psychotherapy.Model
{
    public partial class Contact
    {
        #region Primitive Properties
    
        public virtual int ContactID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> UserID
        {
            get { return _userID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_userID != value)
                    {
                        if (User != null && User.UserID != value)
                        {
                            User = null;
                        }
                        _userID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _userID;
    
        public virtual string Address1
        {
            get;
            set;
        }
    
        public virtual string Address2
        {
            get;
            set;
        }
    
        public virtual string City
        {
            get;
            set;
        }
    
        public virtual string state_province
        {
            get;
            set;
        }
    
        public virtual string country
        {
            get;
            set;
        }
    
        public virtual string post_code
        {
            get;
            set;
        }
    
        public virtual string email
        {
            get;
            set;
        }
    
        public virtual string home_phone
        {
            get;
            set;
        }
    
        public virtual string biz_phone
        {
            get;
            set;
        }
    
        public virtual string mobile_phone
        {
            get;
            set;
        }
    
        public virtual string fax
        {
            get;
            set;
        }
    
        public virtual string alt_phone1
        {
            get;
            set;
        }
    
        public virtual string alt_phone2
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> time_created
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> last_modified
        {
            get;
            set;
        }
    
        public virtual int last_modified_by
        {
            get;
            set;
        }
    
        public virtual bool is_valid
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.Contacts.Contains(this))
            {
                previousValue.Contacts.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.Contacts.Contains(this))
                {
                    User.Contacts.Add(this);
                }
                if (UserID != User.UserID)
                {
                    UserID = User.UserID;
                }
            }
            else if (!_settingFK)
            {
                UserID = null;
            }
        }

        #endregion
    }
}
