//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Insourcia.Psychotherapy.Model
{
    public partial class UserPatientPermission
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int UserID
        {
            get { return _userID; }
            set
            {
                if (_userID != value)
                {
                    if (User != null && User.UserID != value)
                    {
                        User = null;
                    }
                    _userID = value;
                }
            }
        }
        private int _userID;
    
        public virtual int PatientID
        {
            get { return _patientID; }
            set
            {
                if (_patientID != value)
                {
                    if (Patient != null && Patient.PatientID != value)
                    {
                        Patient = null;
                    }
                    _patientID = value;
                }
            }
        }
        private int _patientID;
    
        public virtual bool can_read
        {
            get;
            set;
        }
    
        public virtual bool can_write
        {
            get;
            set;
        }
    
        public virtual bool can_remove
        {
            get;
            set;
        }
    
        public virtual bool can_download
        {
            get;
            set;
        }
    
        public virtual bool can_annotate
        {
            get;
            set;
        }
    
        public virtual bool can_upload
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> time_created
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> last_modified
        {
            get;
            set;
        }
    
        public virtual int last_modified_by
        {
            get;
            set;
        }
    
        public virtual bool is_valid
        {
            get;
            set;
        }
    
        public virtual string FormData
        {
            get;
            set;
        }
    
        public virtual string TreatmentPlanData
        {
            get;
            set;
        }
    
        public virtual string ScannedFormData
        {
            get;
            set;
        }
    
        public virtual string ChartData
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Patient Patient
        {
            get { return _patient; }
            set
            {
                if (!ReferenceEquals(_patient, value))
                {
                    var previousValue = _patient;
                    _patient = value;
                    FixupPatient(previousValue);
                }
            }
        }
        private Patient _patient;
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion
        #region Association Fixup
    
        private void FixupPatient(Patient previousValue)
        {
            if (previousValue != null && previousValue.UserPatientPermissions.Contains(this))
            {
                previousValue.UserPatientPermissions.Remove(this);
            }
    
            if (Patient != null)
            {
                if (!Patient.UserPatientPermissions.Contains(this))
                {
                    Patient.UserPatientPermissions.Add(this);
                }
                if (PatientID != Patient.PatientID)
                {
                    PatientID = Patient.PatientID;
                }
            }
        }
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.UserPatientPermissions.Contains(this))
            {
                previousValue.UserPatientPermissions.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.UserPatientPermissions.Contains(this))
                {
                    User.UserPatientPermissions.Add(this);
                }
                if (UserID != User.UserID)
                {
                    UserID = User.UserID;
                }
            }
        }

        #endregion
    }
}
