//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Insourcia.Psychotherapy.Model
{
    public partial class UserPayment
    {
        #region Primitive Properties
    
        public virtual int PaymentID
        {
            get;
            set;
        }
    
        public virtual int AccountID
        {
            get { return _accountID; }
            set
            {
                if (_accountID != value)
                {
                    if (Account != null && Account.AccountID != value)
                    {
                        Account = null;
                    }
                    _accountID = value;
                }
            }
        }
        private int _accountID;
    
        public virtual double AmountInvoiced
        {
            get;
            set;
        }
    
        public virtual Nullable<double> AmountPaid
        {
            get;
            set;
        }
    
        public virtual double AmountLess
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> PaymentDate
        {
            get;
            set;
        }
    
        public virtual int billing_contact_id
        {
            get;
            set;
        }
    
        public virtual string BillingInfo
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> time_created
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> last_modified
        {
            get;
            set;
        }
    
        public virtual int last_modified_by
        {
            get;
            set;
        }
    
        public virtual bool is_valid
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Account Account
        {
            get { return _account; }
            set
            {
                if (!ReferenceEquals(_account, value))
                {
                    var previousValue = _account;
                    _account = value;
                    FixupAccount(previousValue);
                }
            }
        }
        private Account _account;

        #endregion
        #region Association Fixup
    
        private void FixupAccount(Account previousValue)
        {
            if (previousValue != null && previousValue.UserPayments.Contains(this))
            {
                previousValue.UserPayments.Remove(this);
            }
    
            if (Account != null)
            {
                if (!Account.UserPayments.Contains(this))
                {
                    Account.UserPayments.Add(this);
                }
                if (AccountID != Account.AccountID)
                {
                    AccountID = Account.AccountID;
                }
            }
        }

        #endregion
    }
}
