//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Insourcia.Psychotherapy.Model
{
    public partial class UserTreatmentPlanPermission
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TreatmentPlanID
        {
            get { return _treatmentPlanID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_treatmentPlanID != value)
                    {
                        if (TreatmentPlan != null && TreatmentPlan.TreatmentPlanID != value)
                        {
                            TreatmentPlan = null;
                        }
                        _treatmentPlanID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _treatmentPlanID;
    
        public virtual int UserID
        {
            get { return _userID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_userID != value)
                    {
                        if (User != null && User.UserID != value)
                        {
                            User = null;
                        }
                        _userID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _userID;
    
        public virtual bool can_read
        {
            get;
            set;
        }
    
        public virtual bool can_write
        {
            get;
            set;
        }
    
        public virtual bool can_remove
        {
            get;
            set;
        }
    
        public virtual bool can_download
        {
            get;
            set;
        }
    
        public virtual bool can_annotate
        {
            get;
            set;
        }
    
        public virtual bool can_upload
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> time_created
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> last_modified
        {
            get;
            set;
        }
    
        public virtual int last_modified_by
        {
            get;
            set;
        }
    
        public virtual bool is_valid
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual TreatmentPlan TreatmentPlan
        {
            get { return _treatmentPlan; }
            set
            {
                if (!ReferenceEquals(_treatmentPlan, value))
                {
                    var previousValue = _treatmentPlan;
                    _treatmentPlan = value;
                    FixupTreatmentPlan(previousValue);
                }
            }
        }
        private TreatmentPlan _treatmentPlan;
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupTreatmentPlan(TreatmentPlan previousValue)
        {
            if (previousValue != null && previousValue.UserTreatmentPlanPermissions.Contains(this))
            {
                previousValue.UserTreatmentPlanPermissions.Remove(this);
            }
    
            if (TreatmentPlan != null)
            {
                if (!TreatmentPlan.UserTreatmentPlanPermissions.Contains(this))
                {
                    TreatmentPlan.UserTreatmentPlanPermissions.Add(this);
                }
                if (TreatmentPlanID != TreatmentPlan.TreatmentPlanID)
                {
                    TreatmentPlanID = TreatmentPlan.TreatmentPlanID;
                }
            }
            else if (!_settingFK)
            {
                TreatmentPlanID = null;
            }
        }
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.UserTreatmentPlanPermissions.Contains(this))
            {
                previousValue.UserTreatmentPlanPermissions.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.UserTreatmentPlanPermissions.Contains(this))
                {
                    User.UserTreatmentPlanPermissions.Add(this);
                }
                if (UserID != User.UserID)
                {
                    UserID = User.UserID;
                }
            }
        }

        #endregion
    }
}
