//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
using Insourcia.Psychotherapy.Model;
namespace Insourcia.Repository
{
    public partial class PsychotherapyEntities : ObjectContext
    {
        public const string ConnectionString = "name=PsychotherapyEntities";
        public const string ContainerName = "PsychotherapyEntities";
    
        #region Constructors
    
        public PsychotherapyEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public PsychotherapyEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public PsychotherapyEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Account> Accounts
        {
            get { return _accounts  ?? (_accounts = CreateObjectSet<Account>("Accounts")); }
        }
        private ObjectSet<Account> _accounts;
    
        public ObjectSet<AccountPlan> AccountPlans
        {
            get { return _accountPlans  ?? (_accountPlans = CreateObjectSet<AccountPlan>("AccountPlans")); }
        }
        private ObjectSet<AccountPlan> _accountPlans;
    
        public ObjectSet<Category> Categories
        {
            get { return _categories  ?? (_categories = CreateObjectSet<Category>("Categories")); }
        }
        private ObjectSet<Category> _categories;
    
        public ObjectSet<ClinicalService> ClinicalServices
        {
            get { return _clinicalServices  ?? (_clinicalServices = CreateObjectSet<ClinicalService>("ClinicalServices")); }
        }
        private ObjectSet<ClinicalService> _clinicalServices;
    
        public ObjectSet<ClinicalServiceDiagnosi> ClinicalServiceDiagnosis
        {
            get { return _clinicalServiceDiagnosis  ?? (_clinicalServiceDiagnosis = CreateObjectSet<ClinicalServiceDiagnosi>("ClinicalServiceDiagnosis")); }
        }
        private ObjectSet<ClinicalServiceDiagnosi> _clinicalServiceDiagnosis;
    
        public ObjectSet<Contact> Contacts
        {
            get { return _contacts  ?? (_contacts = CreateObjectSet<Contact>("Contacts")); }
        }
        private ObjectSet<Contact> _contacts;
    
        public ObjectSet<Department> Departments
        {
            get { return _departments  ?? (_departments = CreateObjectSet<Department>("Departments")); }
        }
        private ObjectSet<Department> _departments;
    
        public ObjectSet<File> Files
        {
            get { return _files  ?? (_files = CreateObjectSet<File>("Files")); }
        }
        private ObjectSet<File> _files;
    
        public ObjectSet<Form> Forms
        {
            get { return _forms  ?? (_forms = CreateObjectSet<Form>("Forms")); }
        }
        private ObjectSet<Form> _forms;
    
        public ObjectSet<FormData> FormDatas
        {
            get { return _formDatas  ?? (_formDatas = CreateObjectSet<FormData>("FormDatas")); }
        }
        private ObjectSet<FormData> _formDatas;
    
        public ObjectSet<Group> Groups
        {
            get { return _groups  ?? (_groups = CreateObjectSet<Group>("Groups")); }
        }
        private ObjectSet<Group> _groups;
    
        public ObjectSet<LongTermGoal> LongTermGoals
        {
            get { return _longTermGoals  ?? (_longTermGoals = CreateObjectSet<LongTermGoal>("LongTermGoals")); }
        }
        private ObjectSet<LongTermGoal> _longTermGoals;
    
        public ObjectSet<Objective> Objectives
        {
            get { return _objectives  ?? (_objectives = CreateObjectSet<Objective>("Objectives")); }
        }
        private ObjectSet<Objective> _objectives;
    
        public ObjectSet<Patient> Patients
        {
            get { return _patients  ?? (_patients = CreateObjectSet<Patient>("Patients")); }
        }
        private ObjectSet<Patient> _patients;
    
        public ObjectSet<ProcessGuide> ProcessGuides
        {
            get { return _processGuides  ?? (_processGuides = CreateObjectSet<ProcessGuide>("ProcessGuides")); }
        }
        private ObjectSet<ProcessGuide> _processGuides;
    
        public ObjectSet<Site> Sites
        {
            get { return _sites  ?? (_sites = CreateObjectSet<Site>("Sites")); }
        }
        private ObjectSet<Site> _sites;
    
        public ObjectSet<SiteDepartmentUser> SiteDepartmentUsers
        {
            get { return _siteDepartmentUsers  ?? (_siteDepartmentUsers = CreateObjectSet<SiteDepartmentUser>("SiteDepartmentUsers")); }
        }
        private ObjectSet<SiteDepartmentUser> _siteDepartmentUsers;
    
        public ObjectSet<Strategy> Strategies
        {
            get { return _strategies  ?? (_strategies = CreateObjectSet<Strategy>("Strategies")); }
        }
        private ObjectSet<Strategy> _strategies;
    
        public ObjectSet<Symptom> Symptoms
        {
            get { return _symptoms  ?? (_symptoms = CreateObjectSet<Symptom>("Symptoms")); }
        }
        private ObjectSet<Symptom> _symptoms;
    
        public ObjectSet<SystemFunction> SystemFunctions
        {
            get { return _systemFunctions  ?? (_systemFunctions = CreateObjectSet<SystemFunction>("SystemFunctions")); }
        }
        private ObjectSet<SystemFunction> _systemFunctions;
    
        public ObjectSet<TreatmentPlan> TreatmentPlans
        {
            get { return _treatmentPlans  ?? (_treatmentPlans = CreateObjectSet<TreatmentPlan>("TreatmentPlans")); }
        }
        private ObjectSet<TreatmentPlan> _treatmentPlans;
    
        public ObjectSet<TreatmentPlanItem> TreatmentPlanItems
        {
            get { return _treatmentPlanItems  ?? (_treatmentPlanItems = CreateObjectSet<TreatmentPlanItem>("TreatmentPlanItems")); }
        }
        private ObjectSet<TreatmentPlanItem> _treatmentPlanItems;
    
        public ObjectSet<UserCategoryPermission> UserCategoryPermissions
        {
            get { return _userCategoryPermissions  ?? (_userCategoryPermissions = CreateObjectSet<UserCategoryPermission>("UserCategoryPermissions")); }
        }
        private ObjectSet<UserCategoryPermission> _userCategoryPermissions;
    
        public ObjectSet<UserFilePermission> UserFilePermissions
        {
            get { return _userFilePermissions  ?? (_userFilePermissions = CreateObjectSet<UserFilePermission>("UserFilePermissions")); }
        }
        private ObjectSet<UserFilePermission> _userFilePermissions;
    
        public ObjectSet<UserFormDataPermission> UserFormDataPermissions
        {
            get { return _userFormDataPermissions  ?? (_userFormDataPermissions = CreateObjectSet<UserFormDataPermission>("UserFormDataPermissions")); }
        }
        private ObjectSet<UserFormDataPermission> _userFormDataPermissions;
    
        public ObjectSet<UserPatientPermission> UserPatientPermissions
        {
            get { return _userPatientPermissions  ?? (_userPatientPermissions = CreateObjectSet<UserPatientPermission>("UserPatientPermissions")); }
        }
        private ObjectSet<UserPatientPermission> _userPatientPermissions;
    
        public ObjectSet<UserPayment> UserPayments
        {
            get { return _userPayments  ?? (_userPayments = CreateObjectSet<UserPayment>("UserPayments")); }
        }
        private ObjectSet<UserPayment> _userPayments;
    
        public ObjectSet<UserTreatmentPlanPermission> UserTreatmentPlanPermissions
        {
            get { return _userTreatmentPlanPermissions  ?? (_userTreatmentPlanPermissions = CreateObjectSet<UserTreatmentPlanPermission>("UserTreatmentPlanPermissions")); }
        }
        private ObjectSet<UserTreatmentPlanPermission> _userTreatmentPlanPermissions;
    
        public ObjectSet<UserType> UserTypes
        {
            get { return _userTypes  ?? (_userTypes = CreateObjectSet<UserType>("UserTypes")); }
        }
        private ObjectSet<UserType> _userTypes;
    
        public ObjectSet<Cluster> Clusters
        {
            get { return _clusters  ?? (_clusters = CreateObjectSet<Cluster>("Clusters")); }
        }
        private ObjectSet<Cluster> _clusters;
    
        public ObjectSet<ClinicalServiceNoteRate> ClinicalServiceNoteRates
        {
            get { return _clinicalServiceNoteRates  ?? (_clinicalServiceNoteRates = CreateObjectSet<ClinicalServiceNoteRate>("ClinicalServiceNoteRates")); }
        }
        private ObjectSet<ClinicalServiceNoteRate> _clinicalServiceNoteRates;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public ObjectSet<LogRecord> LogRecords
        {
            get { return _logRecords  ?? (_logRecords = CreateObjectSet<LogRecord>("LogRecords")); }
        }
        private ObjectSet<LogRecord> _logRecords;
    
        public ObjectSet<GlanceAndGuideline> GlanceAndGuidelines
        {
            get { return _glanceAndGuidelines  ?? (_glanceAndGuidelines = CreateObjectSet<GlanceAndGuideline>("GlanceAndGuidelines")); }
        }
        private ObjectSet<GlanceAndGuideline> _glanceAndGuidelines;

        #endregion
    }
}
